### ISSUE TITLE
Add axe

### ISSUE THREAD

**Issue by jhonny17** [jhonny17/mono-repo#49]
## Description

It's a simple task, add axe library.

## Tasks

- [x] Add `axe` library and set it up in the Party Travel project
- [x] Add axe tests
- [x] Make sure there are no violations
